# Generated by Django 5.2.6 on 2025-09-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_alter_transaction_amount_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
